require('./bootstrap');
require('./partials/datepicker');
require('./partials/maps');
require('./partials/chart');
require('./partials/image');
require('./partials/braintree');
require('./partials/bootstrap-fileinput.js');
require('./partials/scrollReveal.js');
require('./partials/commons');
